### ISSUE TITLE
RFC: storing data, sideloading and what to return

### ISSUE THREAD

**Issue by ArnaudWeyts** [teamleadercrm/react-hooks-api#13]
# What

This proposal will serve as documentation and a place to discuss how the implementation works. What do we return as the `data` object, how is the data stored under the hood and how is sideloading handled?

# Proposal

Already partially implemented in #11.

### Normalized entities and queries

Entities will be written to a redux store, normalized by id. This way it's easy to do lookups and we avoid duplicate data. This is generally considered a best practice.

Next to the `entities` state, we also have a `queries` state. This is also an object containing all the queries that have been requested. This is where we will store the id (or ids) relevant to the query.

Here's an example of what the state could look like:

```js
{
  entities: {
    projects: {
      '708c8008-3455-49a9-b66a-5222bcadb0cc': {
        id: '708c8008-3455-49a9-b66a-5222bcadb0cc',
        title: 'Test project'
      },
       'e6538393-aa7e-4ec2-870b-f75b3d85f706': {
        id: 'e6538393-aa7e-4ec2-870b-f75b3d85f706',
        title: 'Test project2'
      }
    }
  }
  queries: {
    '{"domain":"projects","action":"list"}': {
      loading: false,
      ids: ['708c8008-3455-49a9-b66a-5222bcadb0cc', 'e6538393-aa7e-4ec2-870b-f75b3d85f706'],
      meta: {
        matches: 50
      }
    }
  }
}
```

#### Why use a normalized entities state?

By using a normalized state for entities, we can make sure that there's a single source of truth. This can be especially important when updating data. When we provide a way to do update requests using a new hook (hint, hint, `useMutation`), some existing state that can be shared between multiple queries will have to be updated.

## Sideloading

See #12 

To take advantage of sideloading, but retain our normalized entities state, we need to be able to combine the data when selecting it. This is implemented in the referenced PR above, but as @duivvv mentioned, being able to merge sideloaded data is something that is also needed in [sdk-js](https://github.com/teamleadercrm/sdk-js). 

As `react-hooks-api` is mostly a wrapper around `sdk-js`, it makes sense to create an exported plugin called `merge` in the sdk-js repo that can be used to select and merge the included data. See RFC [sdk-js#31](https://github.com/teamleadercrm/sdk-js/issues/31).

The only issue with this approach is the mapping between the singular form of an entity (`company`, which is included in the sideloading reference) and the plural form, or "domain" (`companies`), see the RFC for more context.

## Returned data

Now how will we return the data? I personally don't see a use case (yet) to not return the data merged.

_example hook_
```js
  const QUERY = () => ({
    domain: 'projects',
    action: 'list',
    options: {
      include: 'participant'
    }
  });

  const { loading, error, data } = useQuery(QUERY)
```

_example `data` returned from the hook_
```js
[
  {
     id: '708c8008-3455-49a9-b66a-5222bcadb0cc',
     title: 'Test project'
     participant: {
        type: 'user',
        id: '82200479-576f-462c-ad38-aad52da23c55',
        lastName: 'Smith'
     }
  },
  {
     id: 'e6538393-aa7e-4ec2-870b-f75b3d85f706',
     title: 'Test project'
     participant: {
        type: 'user',
        id: '3defbb8a-c1db-465c-bc25-b36f48894e23',
        lastName: 'Wick'
     }
  }
]
```

-----------
So what do you guys think? Is this a good approach? Do you see any caveats that could come back and haunt us?

**Comment by rathesDot** [comment]
Can you elaborate on what the purpose of the `queries` object is?

```
  queries: {
    '{"domain":"projects","action":"list"}': {
      loading: false,
      ids: ['708c8008-3455-49a9-b66a-5222bcadb0cc', 'e6538393-aa7e-4ec2-870b-f75b3d85f706'],
      meta: {
        matches: 50
      }
    }
  }
```

If I understand you correctly the entries are a mix of request information + intermediate `loading`/`error` states?

**Comment by Kemosabert** [comment]
I think this looks great @ArnaudWeyts , but I don't really agree with your point that there is no use case for not returning side loaded data merged. I personally like the approach of having the side loaded data separated and have them stored in their respective domain because to merge data or access data from other domains we can use selectors. I think it also creates a bit more loosely coupled components as they don't expect the full object from their parent but just an id and a type. 

I think we should have the option to define how we want to receive the side loaded data, as per the proposal in `sdk-js`

EDIT: I realise that when you use immutable-js you lose the memoization advantage of reselect, but I still think it's nice to have the option.

**Comment by ArnaudWeyts** [comment]
@rathesDot the queries object stores information unique to a single query, in the case of the example it stores information unique to that specific `projects.list` request. When a filter is added, a different query will be created, as the ids / meta object are unique to that request. The errors/loading states are also unique per request, hence why I also store them there. Doing it this way, we can avoid doing duplicate requests in the future when two identical queries are being sent out simultaneously (not 100% sure yet how this would work though)

**Comment by ArnaudWeyts** [comment]
@Kemosabert @duivvv You're 100% correct, and at the store level, data is still saved under its respective domain, only the data returned from the actual hook will be merged. We can definitely define an option in a future version where you can supply your own selector, that way you have full control over the store and what data is returned.

**Comment by ArnaudWeyts** [comment]
Available in https://github.com/teamleadercrm/react-hooks-api/releases/tag/0.1.0-rc1
