### ISSUE TITLE
RFC: non-standard CRUD endpoints in the entity store

### ISSUE THREAD

**Issue by ArnaudWeyts** [teamleadercrm/react-hooks-api#78]
# What

This proposal is related to #13.

There's a working implementation of #13, but we never discussed non-conventional `CRUD` endpoints like `.report` or other future endpoints. How do we handle calculation endpoints like these? Where do they belong in the store?

This RFC served more as a write-up for myself and documentation. Scroll down to see the actual proposal.

# Proposal

## Storing the returned data

Our store is a normalized entity store. This means entities are stored using a unique identifier. In our case: their UUID. What gets returned from f.e. `projectItems.report` is:

```json
{
  "data": {
    "billableAmount": {
       "amount": 1644.65,
       "currency": "EUR"
     },
    "result": {
       "amount": -195.35,
       "currency": "EUR"
    },
    "cost": {
       "amount": 1840,
       "currency": "EUR"
    },
    "quantity": 28,
    "type": "tracked_time",
     "unit": "hour",
    "participant": {
      "type": "user",
      "id": "d2886235-61f8-4c77-8e6f-d55f4c91f501"
    }
  }
```

There's nothing here to really identify this calculation by. As it's "just" a calculation at that point in time. It's not stored in the database, it's not an entity.

So let's first find something to identify this calculation by. We could generate an ID based on the parameters passed in the request body:

In the case of `projectItems.report` this is
   * `milestone_id`
   * `group_by` (an enum)
   * (maybe the timestamp of the request)

While I was writing this down, it dawned on me that we can just store the returned data inside our `queries` state object. It makes sense, since we're already generating a "unique" id for each query. This makes sure we don't pollute our `entity` store with calculation data.

## So here comes the actual proposal

Only try to store actual `entities` inside the `entities` state object. Makes a lot of sense right? Inside of `useQuery` I'll be adding a check if the `action` is of the type `info` or `list`. And every other action will result in the response being set inside the `queries` object, under their respective query identifier.

**Comment by rathesDot** [comment]
But what will happen if there are endpoints that return entities but do not have the regular pattern? For example, `invites.accept` might return a user entity or `account.create` or `account.setup` might return account entities

**Comment by ArnaudWeyts** [comment]
@rathesDot I suppose that means they can be added to the list of actions that actually returns an entity?

**Comment by ArnaudWeyts** [comment]
But those endpoints seem like a better fit for the upcoming `useMutation` hook, as they're actually creating / mutating something

**Comment by rathesDot** [comment]
> @rathesDot I suppose that means they can be added to the list of actions that actually returns an entity?

What do you mean with this?

**Comment by rathesDot** [comment]
> But those endpoints seem like a better fit for the upcoming `useMutation` hook, as they're actually creating / mutating something

Yeah, this would make sense, I think

**Comment by ArnaudWeyts** [comment]
> > @rathesDot I suppose that means they can be added to the list of actions that actually returns an entity?
> 
> What do you mean with this?

I'll be adding a check in `useQuery` to decide wether or not to set the entity in the entity state, or on a query level, very roughly something like:

```js
if (action === 'info' || action === 'list') {
   ...insert in entity state
} else {
   ...insert in query state
}
```

**Comment by rathesDot** [comment]
Will that be hard-coded, or will that be a configurable map?

**Comment by ArnaudWeyts** [comment]
> Will that be hard-coded, or will that be a configurable map?

Hard coded for now, possibly configurable in the future

**Comment by ArnaudWeyts** [comment]
Available in https://github.com/teamleadercrm/react-hooks-api/releases/tag/0.1.0-rc1
